cmake_minimum_required(VERSION 3.16)

set(PLATFORM_LINUX 0)
set(PLATFORM_WINDOWS 0)
set(PLATFORM_OSX 0)
if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  set(PLATFORM_LINUX 1)
  set(PLATFORM_NAME "linux")
elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
  set(PLATFORM_WINDOWS 1)
  set(PLATFORM_NAME "windows")
elseif (CMAKE_SYSTEM_NAME MATCHES "Darwin")
  set(PLATFORM_OSX 1)
  set(PLATFORM_NAME "osx")

  set(CMAKE_OSX_DEPLOYMENT_TARGET "10.13")
endif()
