cmake_minimum_required(VERSION 3.16)
include(ExternalProject)
include(common)

set(
  GLFW_CMAKE_ARGS
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
  -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
  -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
)

ExternalProject_Add(
  libglfw
  URL https://github.com/glfw/glfw/archive/3.3.2.tar.gz
  PREFIX glfw_src
  CMAKE_ARGS ${GLFW_CMAKE_ARGS}
  INSTALL_DIR ${PROJECT_BINARY_DIR}/glfw_bin
  LOG_CONFIGURE 1
  LOG_BUILD 1
  LOG_INSTALL 1
)
